<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Booking Report</title>

    <style>

        body{
            font-family: Arial, sans-serif;
            font-size: 13px;
            color:#333;
            padding:20px;
        }

        .header{
            text-align:center;
            margin-bottom:30px;
        }

        .header h1{
            margin:0;
            font-size:28px;
        }

        .header p{
            margin-top:8px;
            color:#666;
        }

        .section{
            margin-bottom:25px;
        }

        .section h3{
            margin-bottom:12px;
            font-size:16px;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        table, th, td{
            border:1px solid #000;
        }

        th{
            background:#f3f4f6;
            text-align:left;
            padding:10px;
        }

        td{
            padding:10px;
        }

        .footer{
            margin-top:40px;
            text-align:center;
            font-size:11px;
            color:#777;
        }

    </style>

</head>

<body>

    <!-- HEADER -->
    <div class="header">

        <h1>Tutor Booking Report</h1>

        <p>
            Official Booking Record
        </p>

    </div>



    <!-- BOOKING DETAILS -->
    <div class="section">

        <h3>Booking Information</h3>

        <table>

            <tr>

                <th style="width:30%;">
                    Booking ID
                </th>

                <td>
                    #{{ $booking->id }}
                </td>

            </tr>


            <tr>

                <th>
                    Student Name
                </th>

                <td>
                    {{ $booking->student->name ?? 'N/A' }}
                </td>

            </tr>



            <tr>

                <th>
                    Tutor Name
                </th>

                <td>
                    {{ $booking->tutor->user->name ?? 'N/A' }}
                </td>

            </tr>



            <tr>

                <th>
                    Subject
                </th>

                <td>
                    {{ $booking->subject->name ?? 'N/A' }}
                </td>

            </tr>



            <tr>

                <th>
                    Session Date
                </th>

                <td>
                    {{ $booking->session_date }}
                </td>

            </tr>



            <tr>

                <th>
                    Status
                </th>

                <td>
                    {{ ucfirst($booking->status) }}
                </td>

            </tr>



            <tr>

                <th>
                    Created At
                </th>

                <td>
                    {{ $booking->created_at->format('d M Y') }}
                </td>

            </tr>

        </table>

    </div>



    <!-- FOOTER -->
    <div class="footer">

        Generated by Tutor Finder

    </div>

</body>

</html>